### ISSUE TITLE
help!!

### ISSUE THREAD

**Issue by elementalwow** [namreeb/wowned#15]
Hello I try to run wowned.exe it opens and closes quickly, could you explain to me how to solve?

**Comment by GuillaumeHemmen** [comment]
Have you launched it using the CLI as advised in the [README](https://github.com/namreeb/wowned/blob/master/README.md) ?

**Comment by elementalwow** [comment]
I extract the wowned files from my wow local folder, run wowned.exe and it closes quickly, am i doing wrong? if you can explain me I appreciate

**Comment by elementalwow** [comment]
![image](https://user-images.githubusercontent.com/57023516/69981855-ed6a1080-1511-11ea-9e59-8b9cf69a16ba.png)
show it, and close quickly.

**Comment by GuillaumeHemmen** [comment]
Well if you run it by clicking on it it will not work. You must use a terminal (`cmd` on windows) to run the program with the needed arguments as explained in the readme document.

If you are not familiar with the terminal a quick search with your favorite search engine will help you to get started: https://duckduckgo.com/?q=basic+use+of+windows+cmd

Be warned though: most of the private server should have this issue fixed since the time it was released...

**Comment by GuillaumeHemmen** [comment]
If you are not familiar with the terminal a quick search with your favorite search engine will help you to get started: https://duckduckgo.com/?q=basic+use+of+windows+cmd

**Comment by neltharionbr** [comment]
![image](https://user-images.githubusercontent.com/57023516/69983298-1b9d1f80-1515-11ea-96a4-e531b5631e9e.png)
error

**Comment by elementalwow** [comment]
I applied I put login and any password to try to login, and disconnects me from the server.

**Comment by namreeb** [comment]
> ![image](https://user-images.githubusercontent.com/57023516/69981855-ed6a1080-1511-11ea-9e59-8b9cf69a16ba.png)
> show it, and close quickly.

The error is shown in the output:
`ERROR: No method chosen`

This exploit is actually two in one as there were two similar bugs found at more-or-less the same time.  You have to specify `--1` or `--2` when running.
