### ISSUE TITLE
1.12.3 Possibly supported?

### ISSUE THREAD

**Issue by ryancheung** [namreeb/wowned#7]
May 1.12.3 be  supported? @namreeb

**Comment by namreeb** [comment]
I mean I could, but would it really help you?  Don't most servers have this patched now?

**Comment by ryancheung** [comment]
@namreeb Yes, It actually helps me if you can add support for 1.12.3, I found some servers using 1.12.3.
Appreciate!

**Comment by ryancheung** [comment]
@namreeb I placed a bounty in https://www.bountysource.com/issues/45396939-1-12-3-possibly-supported
Appreciate if you're available to add 1.12.3 support.

If you need source to download 1.12.3 client you could tell me here.
Thank you!

**Comment by namreeb** [comment]
I am somewhat conflicted about the ethics of this. On the one hand, by now any server who hasn't patched deserves their fate. On the other hand, taking money to adapt an exploit is a little more black hat than I normally behave. Especially since the value of this bounty is probably calculated to not eat into the profits you might come into were you to have this ability. 

I think I will pass.

Furthermore, I would strongly encourage you to disclose this vulnerability as well as the existing fixes for it to any affected servers you have found. 

I'm closing this as at this point I am ready to say that I will not address issue. I invite you to continue discussion here if you so desire.

**Comment by ryancheung** [comment]
As you pass, I'll pass too. I'll switch to spending time for more meaningful things. Thanks anyway!
